### PR TITLE
WIP Render annotations

### PR DESCRIPTION
**Pull request by paurosello**
Towards https://github.com/giantswarm/giantswarm/issues/14222

https://github.com/giantswarm/apiextensions/pull/679/ is needed to render docs with annotations

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by marians** [comment]
Can you please link from here to the issue this PR is for? Thx

**Comment by marians** [comment]
Found the issue again and updated the description

**Comment by paurosello** [comment]
@marians I think we are ready to merge this one

**Comment by marians** [comment]
In order to apply this to docs, please update https://github.com/giantswarm/docs/blob/master/scripts/update-crd-reference/crd.template with the template additions.

As of recently, the template here in this repo is only considered an example.

**Review by marians — APPROVED** [review]
Fine if it works for you

**Pull request merged**
